# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FacebookLogin' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for FacebookLogin
  pod 'FBSDKLoginKit'
  pod 'Parse'

  target 'FacebookLoginTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FacebookLoginUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
