# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'loginFBtest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for loginFBtest

    pod 'FBSDKLoginKit'

  target 'loginFBtestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'loginFBtestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
