# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PostingBookDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PostingBookDemo

  pod 'BDBOAuth1Manager'
  pod 'Parse'
  pod 'ParseUI'

  target 'PostingBookDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PostingBookDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
